# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(261, 359)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 3, 261, 461))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui/img/noclass.png"))
        self.label.setObjectName("label")
        self.settings = QtWidgets.QPushButton(Dialog)
        self.settings.setGeometry(QtCore.QRect(50, 123, 161, 23))
        self.settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/img/sett.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings.setIcon(icon)
        self.settings.setIconSize(QtCore.QSize(200, 150))
        self.settings.setObjectName("settings")
        self.binds = QtWidgets.QPushButton(Dialog)
        self.binds.setGeometry(QtCore.QRect(137, 164, 71, 23))
        self.binds.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.binds.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/img/binds.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.binds.setIcon(icon1)
        self.binds.setIconSize(QtCore.QSize(200, 150))
        self.binds.setObjectName("binds")
        self.change_class = QtWidgets.QPushButton(Dialog)
        self.change_class.setGeometry(QtCore.QRect(50, 163, 71, 23))
        self.change_class.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_class.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui/img/class.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_class.setIcon(icon2)
        self.change_class.setIconSize(QtCore.QSize(200, 150))
        self.change_class.setObjectName("change_class")
        self.start = QtWidgets.QPushButton(Dialog)
        self.start.setGeometry(QtCore.QRect(50, 299, 151, 31))
        self.start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui/img/start.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon3)
        self.start.setIconSize(QtCore.QSize(200, 150))
        self.start.setObjectName("start")
        self.info = QtWidgets.QPushButton(Dialog)
        self.info.setGeometry(QtCore.QRect(208, 71, 21, 20))
        self.info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.info.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui/img/info.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info.setIcon(icon4)
        self.info.setIconSize(QtCore.QSize(200, 150))
        self.info.setObjectName("info")
        self.close = QtWidgets.QPushButton(Dialog)
        self.close.setGeometry(QtCore.QRect(220, 30, 21, 20))
        self.close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ui/img/close.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon5)
        self.close.setIconSize(QtCore.QSize(200, 150))
        self.close.setObjectName("close")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 240, 141, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("ui/img/hider.png"))
        self.label_2.setObjectName("label_2")
        self.start_wow = QtWidgets.QPushButton(Dialog)
        self.start_wow.setGeometry(QtCore.QRect(70, 212, 96, 31))
        self.start_wow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_wow.setAutoFillBackground(False)
        self.start_wow.setStyleSheet("background-color: transpanent;")
        self.start_wow.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ui/img/start_wow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_wow.setIcon(icon6)
        self.start_wow.setIconSize(QtCore.QSize(116, 102))
        self.start_wow.setObjectName("start_wow")
        self.wow_text = QtWidgets.QLabel(Dialog)
        self.wow_text.setGeometry(QtCore.QRect(30, 249, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Futura-Normal")
        font.setPointSize(12)
        self.wow_text.setFont(font)
        self.wow_text.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.wow_text.setStyleSheet("color: green")
        self.wow_text.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.wow_text.setObjectName("wow_text")
        self.reload = QtWidgets.QPushButton(Dialog)
        self.reload.setGeometry(QtCore.QRect(170, 218, 21, 20))
        self.reload.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reload.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ui/img/reload.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reload.setIcon(icon7)
        self.reload.setIconSize(QtCore.QSize(200, 150))
        self.reload.setObjectName("reload")
        self.bug_report = QtWidgets.QPushButton(Dialog)
        self.bug_report.setGeometry(QtCore.QRect(108, 68, 82, 26))
        self.bug_report.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bug_report.setAutoFillBackground(False)
        self.bug_report.setStyleSheet("background-color: transpanent;")
        self.bug_report.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("ui/img/bug_report.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bug_report.setIcon(icon8)
        self.bug_report.setIconSize(QtCore.QSize(116, 102))
        self.bug_report.setObjectName("bug_report")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.wow_text.setText(_translate("Dialog", "WoW is not started"))


