# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spec.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(585, 537)
        self.bg = QtWidgets.QLabel(Dialog)
        self.bg.setGeometry(QtCore.QRect(50, 30, 501, 471))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("ui/img/class/ccfront.jpg"))
        self.bg.setObjectName("bg")
        self.dk = QtWidgets.QPushButton(Dialog)
        self.dk.setGeometry(QtCore.QRect(70, 100, 111, 101))
        self.dk.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dk.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/img/class/buttons/dk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dk.setIcon(icon)
        self.dk.setIconSize(QtCore.QSize(150, 150))
        self.dk.setObjectName("dk")
        self.dru = QtWidgets.QPushButton(Dialog)
        self.dru.setGeometry(QtCore.QRect(200, 93, 81, 111))
        self.dru.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dru.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/img/class/buttons/dru.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dru.setIcon(icon1)
        self.dru.setIconSize(QtCore.QSize(150, 150))
        self.dru.setObjectName("dru")
        self.hun = QtWidgets.QPushButton(Dialog)
        self.hun.setGeometry(QtCore.QRect(318, 94, 81, 111))
        self.hun.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hun.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui/img/class/buttons/hun.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hun.setIcon(icon2)
        self.hun.setIconSize(QtCore.QSize(150, 150))
        self.hun.setObjectName("hun")
        self.mag = QtWidgets.QPushButton(Dialog)
        self.mag.setGeometry(QtCore.QRect(436, 93, 81, 111))
        self.mag.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mag.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui/img/class/buttons/mag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mag.setIcon(icon3)
        self.mag.setIconSize(QtCore.QSize(150, 150))
        self.mag.setObjectName("mag")
        self.pri = QtWidgets.QPushButton(Dialog)
        self.pri.setGeometry(QtCore.QRect(85, 214, 81, 111))
        self.pri.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pri.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui/img/class/buttons/pri.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pri.setIcon(icon4)
        self.pri.setIconSize(QtCore.QSize(150, 150))
        self.pri.setObjectName("pri")
        self.rog = QtWidgets.QPushButton(Dialog)
        self.rog.setGeometry(QtCore.QRect(200, 214, 81, 111))
        self.rog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rog.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ui/img/class/buttons/rog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rog.setIcon(icon5)
        self.rog.setIconSize(QtCore.QSize(150, 150))
        self.rog.setObjectName("rog")
        self.sha = QtWidgets.QPushButton(Dialog)
        self.sha.setGeometry(QtCore.QRect(318, 213, 81, 111))
        self.sha.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sha.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ui/img/class/buttons/sha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sha.setIcon(icon6)
        self.sha.setIconSize(QtCore.QSize(150, 150))
        self.sha.setObjectName("sha")
        self.warl = QtWidgets.QPushButton(Dialog)
        self.warl.setGeometry(QtCore.QRect(434, 214, 81, 111))
        self.warl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.warl.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ui/img/class/buttons/warl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.warl.setIcon(icon7)
        self.warl.setIconSize(QtCore.QSize(150, 150))
        self.warl.setObjectName("warl")
        self.warr = QtWidgets.QPushButton(Dialog)
        self.warr.setGeometry(QtCore.QRect(85, 336, 81, 111))
        self.warr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.warr.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("ui/img/class/buttons/warr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.warr.setIcon(icon8)
        self.warr.setIconSize(QtCore.QSize(150, 150))
        self.warr.setObjectName("warr")
        self.pal = QtWidgets.QPushButton(Dialog)
        self.pal.setGeometry(QtCore.QRect(203, 338, 81, 111))
        self.pal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pal.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("ui/img/class/buttons/pal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pal.setIcon(icon9)
        self.pal.setIconSize(QtCore.QSize(150, 150))
        self.pal.setObjectName("pal")
        self.mon = QtWidgets.QPushButton(Dialog)
        self.mon.setGeometry(QtCore.QRect(315, 336, 81, 111))
        self.mon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mon.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("ui/img/class/buttons/mon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mon.setIcon(icon10)
        self.mon.setIconSize(QtCore.QSize(150, 150))
        self.mon.setObjectName("mon")
        self.dh = QtWidgets.QPushButton(Dialog)
        self.dh.setGeometry(QtCore.QRect(414, 335, 121, 111))
        self.dh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dh.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("ui/img/class/buttons/dh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dh.setIcon(icon11)
        self.dh.setIconSize(QtCore.QSize(150, 150))
        self.dh.setObjectName("dh")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


